### Library

In [1]:
import torch 
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

### 1. Tensor 연산 및 조작

- 1-1. Tensor 간의 계산
- 1-2. Broadcasting 을 이용한 Tensor 값 변경
- 1-3. Broadcasting 을 이용한 차원이 다른 Tensor 간의 계산

#### 1-1. Tensor 간의 계산

In [2]:
tensor_a = torch.tensor([[1, -1], [2, 3]])
tensor_b = torch.tensor([[2, -2] ,[3, 1]])

print('덧셈')
print("a+b : \n", tensor_a + tensor_b)
print('\n')
print("torch.add(a,b) : \n", torch.add(tensor_a, tensor_b))

print('---'*10)

print('뺄셈')
print("a-b : \n", tensor_a - tensor_b)
print('\n')
print("torch.sub(a,b) : \n", torch.sub(tensor_a, tensor_b))

print('---'*10)

print('곱셈')
print("a*b : \n", tensor_a * tensor_b)
print('\n')
print("torch.mul(a,b) : \n", torch.mul(tensor_a, tensor_b))

print('---'*10)

print('나눗셈')
print("a/b : \n", tensor_a / tensor_b)
print('\n')
print("torch.div(a,b) : \n", torch.div(tensor_a, tensor_b))

덧셈
a+b : 
 tensor([[ 3, -3],
        [ 5,  4]])


torch.add(a,b) : 
 tensor([[ 3, -3],
        [ 5,  4]])
------------------------------
뺄셈
a-b : 
 tensor([[-1,  1],
        [-1,  2]])


torch.sub(a,b) : 
 tensor([[-1,  1],
        [-1,  2]])
------------------------------
곱셈
a*b : 
 tensor([[2, 2],
        [6, 3]])


torch.mul(a,b) : 
 tensor([[2, 2],
        [6, 3]])
------------------------------
나눗셈
a/b : 
 tensor([[0.5000, 0.5000],
        [0.6667, 3.0000]])


torch.div(a,b) : 
 tensor([[0.5000, 0.5000],
        [0.6667, 3.0000]])


- sum: Tensor의 원소들의 합을 return 함

In [3]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

print("dimension 지정 안했을 때 : ", torch.sum(tensor_a))  # 모든 원소의 합을 반환 함
print("dim = 0 일 때 : ", torch.sum(tensor_a, dim=0))  # 행을 기준 (행 인덱스 변화)으로 합함 (0행 0열 + 1행 0열, 0행 1열 + 1행 1열)
print("dim = 1 일 때 : ", torch.sum(tensor_a, dim=1)) # 열을 기준 (열 인덱스 변화)으로 합함 (0행 0열 + 0행 1열, 1행 0열 + 1행 1열)

tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])

dimension 지정 안했을 때 :  tensor(10)
dim = 0 일 때 :  tensor([4, 6])
dim = 1 일 때 :  tensor([3, 7])


- mean: Tensor 원소들의 평균을 return 함

In [4]:
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32) # float 지정
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

print("dimension 지정 안했을 때 : ", torch.mean(tensor_a))  # 모든 원소의 평균을 반환
print("dim = 0 일 때 : ", torch.mean(tensor_a, dim=0))  
print("dim = 1 일 때 : ", torch.mean(tensor_a, dim=1)) 

tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])

dimension 지정 안했을 때 :  tensor(2.5000)
dim = 0 일 때 :  tensor([2., 3.])
dim = 1 일 때 :  tensor([1.5000, 3.5000])


- max: Tensor 원소들의 가장 큰 값을 return
- min: Tensor 원소들의 가장 작은 값을 return

In [5]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

print(f"dimension 지정 안했을 때: {torch.max(tensor_a)}")  # 모든 원소 중 최댓값 반환
print(f"dim = 0 일 때: {torch.max(tensor_a, dim=0).values}")  
print(f"dim = 1 일 때: {torch.max(tensor_a, dim=1).values}\n") 

print(f"dimension 지정 안했을 때: {torch.min(tensor_a)}")  # 모든 원소의 최솟값 반환 함
print(f"dim = 0 일 때: {torch.min(tensor_a, dim=0).values}")  
print(f"dim = 1 일 때: {torch.min(tensor_a, dim=1).values}") 

tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])

dimension 지정 안했을 때: 4
dim = 0 일 때: tensor([3, 4])
dim = 1 일 때: tensor([2, 4])

dimension 지정 안했을 때: 1
dim = 0 일 때: tensor([1, 2])
dim = 1 일 때: tensor([1, 3])


- argmax: Tensor 원소들의 가장 큰 값의 위치 반환
- argmin: Tensor 원소들의 가장 작은 값의 위치 반환

In [6]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

print(f"dimension 지정 안했을 때 : {torch.argmax(tensor_a)}")  # 모든 원소 중 최댓값 위치 반환
print(f"dim = 0 일 때 : {torch.argmax(tensor_a, dim=0)}")  
print(f"dim = 1 일 때 : {torch.argmax(tensor_a, dim=1)}\n") 

print(f"dimension 지정 안했을 때 : {torch.argmin(tensor_a)}")  # 모든 원소의 최솟값 위치 반환
print(f"dim = 0 일 때 : {torch.argmin(tensor_a, dim=0)}")  
print(f"dim = 1 일 때 : {torch.argmin(tensor_a, dim=1)}") 

tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])

dimension 지정 안했을 때 : 3
dim = 0 일 때 : tensor([1, 1])
dim = 1 일 때 : tensor([1, 1])

dimension 지정 안했을 때 : 0
dim = 0 일 때 : tensor([0, 0])
dim = 1 일 때 : tensor([0, 0])


- dot: 벡터의 내적 반환

In [7]:
v1 = torch.tensor([1, 2])
u1 = torch.tensor([3, 4])

print(f"V1.dot(u1): {v1.dot(u1)}") # 1x3 + 2x4 = 11
print(f"torch.dot(v1, u1): {torch.dot(v1, u1)}") # 1x3 + 2x4 = 11

V1.dot(u1): 11
torch.dot(v1, u1): 11


- matmul: 두 Tensor 간의 행렬곱 반환
- 원소 곱셈과 다름 주의

In [8]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[-1, 2], [1, 0]])

print(f"A: {A}")
print(f"B: {B}\n")

print(f"AB: {torch.matmul(A, B)}") # A 에서 B를 행렬곱
print(f"BA: {B.matmul(A)}") # B 에서 A를 행렬곱

A: tensor([[1, 2],
        [3, 4]])
B: tensor([[-1,  2],
        [ 1,  0]])

AB: tensor([[1, 2],
        [1, 6]])
BA: tensor([[5, 6],
        [1, 2]])


#### 1-2. Broadcasting 을 이용한 Tensor 값 변경

- scalar 값으로 Tensor 원소 변경

In [9]:
torch_a = torch.rand(3, 2)
print(f"Original Tensor: {torch_a}\n")

torch_a[0, :] = 10 # 0행의 모든 열에 broadcasting 을 통한 scalar 값 대입
print(f"변경된 Tensor: {torch_a}")

Original Tensor: tensor([[0.8637, 0.6219],
        [0.9647, 0.0415],
        [0.9986, 0.9032]])

변경된 Tensor: tensor([[10.0000, 10.0000],
        [ 0.9647,  0.0415],
        [ 0.9986,  0.9032]])


- indexing 으로 Tensor 원소 접근 후 scalar 값으로 원소 변경

In [10]:
tensor_a = torch.randn(3, 2)
print(f"Original Tensor: {tensor_a}\n")

tensor_a[:, :] = torch.tensor([0, 1]) # 모든 값에 접근해서 [0,1] 로 변경
print(f"변경된 Tensor: {tensor_a}")

Original Tensor: tensor([[-1.5824,  0.4951],
        [-1.4963,  0.0228],
        [ 0.8205,  1.1978]])

변경된 Tensor: tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])


### 2. Sparse Tensor 조작

- 2-1. COO Tensor 이해
- 2-2. CSC/CSR Tensor 이해
- 2-3. Sparse Tensor 의 필요성
- 2-4. Sparse Tensor 조작

#### 2-1. COO Tensor 이해

- 구조: 튜플 리스트 형식  
- 저장 내용: (행 인덱스, 열 인덱스, 값)  
- 특징: 구조 단순, 수정과 생성이 쉬움  
- 주로 사용되는 경우: 연산보다는 **데이터 입력/생성 시**

In [11]:
a = torch.tensor([[0, 2], [3, 0]])
a.to_sparse() # COO Sparse Tensor 변환

tensor(indices=tensor([[0, 1],
                       [1, 0]]),
       values=tensor([2, 3]),
       size=(2, 2), nnz=2, layout=torch.sparse_coo)

- `Sparse_coo_tensot`: COO 형식의 Sparse Tensor 를 생성하는 함수
    - indices: 0이 아닌 값을 가진 행, 열의 위치
    - values: 0이 아닌 값
    - nnz: 0이 아닌 값의 개수

In [12]:
indices = torch.tensor([[0, 1, 1], [2, 0, 1]])
values = torch.tensor([4, 5, 6])
sparse_tensor = torch.sparse_coo_tensor(indices=indices, values=values, size=(2, 3))

print(f"{sparse_tensor}\n")
print(sparse_tensor.to_dense())

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 1]]),
       values=tensor([4, 5, 6]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

tensor([[0, 0, 4],
        [5, 6, 0]])


#### 2-2. CSC/CSR Tensor 이해

- CSR
    - 구조: 압축된 행 기반  
    - 저장 내용: 행 포인터, 열 인덱스, 값  
    - 특징: **행 단위 연산**이 빠름  
    - 주로 사용되는 경우: **행 방향 탐색**에 유리 (ML, 분류 등)

- CSC
    - 구조: 압축된 열 기반  
    - 저장 내용: 열 포인터, 행 인덱스, 값  
    - 특징: **열 단위 연산**이 빠름  
    - 주로 사용되는 경우: **열 방향 탐색**에 유리 (선형대수, 수치 해석 등)

- to_sparse_csr : Dense tensor를 CSR 형식의 Sparse tensor로 변환하는 함수
  - crow_indices : 0 이 아닌 값을 가진 행의 위치 (첫번째는 무조건 0)
  - col_indices : 0 이 아닌 값을 가진 열의 위치
  - values : 0 이 아닌 값
  - nnz : 0 이 아닌 값의 개수

In [13]:
t = torch.tensor([[0, 0, 4, 3], [5, 6, 0, 0]])
print(f"Shape: {t.size()}\n")
print(t)

t.to_sparse_csr() # Dense Tensor 를 CSR 형식의 Sparse Tensor 로 변환

Shape: torch.Size([2, 4])

tensor([[0, 0, 4, 3],
        [5, 6, 0, 0]])


tensor(crow_indices=tensor([0, 2, 4]),
       col_indices=tensor([2, 3, 0, 1]),
       values=tensor([4, 3, 5, 6]), size=(2, 4), nnz=4,
       layout=torch.sparse_csr)

In [14]:
t = torch.tensor([[0, 0, 4, 3], [5, 6, 0, 0]])
print(f"Shape: {t.size()}\n")
print(t)

t.to_sparse_csc() # Dense Tensor 를 CSC 형식의 Sparse Tensor 로 변환

Shape: torch.Size([2, 4])

tensor([[0, 0, 4, 3],
        [5, 6, 0, 0]])


tensor(ccol_indices=tensor([0, 1, 2, 3, 4]),
       row_indices=tensor([1, 1, 0, 0]),
       values=tensor([5, 6, 4, 3]), size=(2, 4), nnz=4,
       layout=torch.sparse_csc)

- sparse_csr_tensor: CSR 형식의 Sparse Tensor 를 생성하는 함수

In [15]:
crow_indices = torch.tensor([0, 2, 2]) # 0이 아닌 행의 위치 (첫번쨰는 무조건 0), 즉 row_pointer
col_indices = torch.tensor([0, 1]) # 0이 아닌 열의 위치
values = torch.tensor([1, 2]) # 0이 아닌 값
csr = torch.sparse_csr_tensor(crow_indices = crow_indices, col_indices = col_indices, values = values)

print(csr)
print()
print(csr.to_dense()) # CRS Tensor 를 Dense Tensor 로 변환

tensor(crow_indices=tensor([0, 2, 2]),
       col_indices=tensor([0, 1]),
       values=tensor([1, 2]), size=(2, 2), nnz=2, layout=torch.sparse_csr)

tensor([[1, 2],
        [0, 0]])


#### 2-3. Sparse Tensor 의 필요성

- 큰 크기의 matrix 를 구성할 때 일반적인 Dense Tensor 는 메모리 아웃 현상이 발생하지만
- Sparse Tensor 는 메모리 아웃현상이 발생하지 않음
- `to_dense()`: Saprse Tensor 를 Dense Tensor 로 만드는 함수

In [16]:
i = torch.randint(0, 100000, (200000,)).reshape(2, -1)
v = torch.rand(100000)
coo_sparse_tensor = torch.sparse_coo_tensor(indices = i, values = v, size = [100000, 100000]) # COO Sparse Tensor (100000 x 100000)
coo_sparse_tensor

tensor(indices=tensor([[  542, 64383, 27284,  ..., 34489, 27409, 12997],
                       [41868, 18464, 71441,  ..., 56694, 36771, 69393]]),
       values=tensor([0.5017, 0.6638, 0.5747,  ..., 0.1194, 0.3796, 0.2016]),
       size=(100000, 100000), nnz=100000, layout=torch.sparse_coo)

In [17]:
crow = torch.randint(0, 100000, (100000,))
col = torch.randint(0, 100000, (100000,))
v = torch.rand(100000)
csr_sparse_tensor = torch.sparse_csr_tensor(crow_indices = crow, col_indices = col, values = v) # CSR Sparse Tensor (100000 x 100000)
csr_sparse_tensor

tensor(crow_indices=tensor([ 2685,  5730, 64103,  ...,   266, 91733, 44810]),
       col_indices=tensor([  160, 17354, 71650,  ..., 62978, 17957, 73504]),
       values=tensor([0.6782, 0.1481, 0.6329,  ..., 0.4253, 0.8559, 0.8333]),
       size=(99999, 100000), nnz=100000, layout=torch.sparse_csr)

In [ ]:
# COO > Dense Tensor 로 변환 = 메모리 아웃, 즉 커널 튕김
coo_sparse_tensor.to_dense()

In [19]:
# CSR > Dense Tensor 로 변환 = 메모리 아웃, 즉 커널 튕김
csr_sparse_tensor.to_dense()

#### 2-4. Sparse Tensor 조작

In [20]:
# Sparse 와 Sparse Tensor 간의 연산 (2차원)
a = torch.tensor([[0, 1], [0, 2]], dtype=torch.float)
b = torch.tensor([[1, 0],[0, 0]], dtype=torch.float)

sparse_a = a.to_sparse()
sparse_b = b.to_sparse()

print('덧셈')
print(torch.add(a, b).to_dense() == torch.add(sparse_a, sparse_b).to_dense())

print('\n')
print('곱셈')
print(torch.mul(a, b).to_dense() == torch.mul(sparse_a, sparse_b).to_dense())

print('\n')

print('행렬곱')
print(torch.matmul(a, b).to_dense() == torch.matmul(sparse_a, sparse_b).to_dense())

덧셈
tensor([[True, True],
        [True, True]])


곱셈
tensor([[True, True],
        [True, True]])


행렬곱
tensor([[True, True],
        [True, True]])


- 3차원 sparse tensor 에는 일반 텐서와 동일하게 사칙연산 함수들은 사용 가능하지만 행렬곱을 사용할 수 없음
- CSR/CSC 형식에서는 곱셈도 3차원에선 불가능
- 이는 sparse tensor 와 sparse tensor 간에도 적용이 되고, sparse tensor 와 dense tensor 간의 연산에도 적용이 가능

In [21]:
# Sparse 와 Sparse Tensor 간의 연산 (3차원)
a = torch.tensor([[[0, 1], [0, 2]], [[0, 1], [0, 2]]], dtype=torch.float)
b = torch.tensor([[[1, 0],[0, 0]], [[1, 0], [0, 0]]], dtype=torch.float)

sparse_a = a.to_sparse()
sparse_b = b.to_sparse()

print('덧셈')
print(torch.add(a, b).to_dense() == torch.add(sparse_a, sparse_b).to_dense())

print('\n')
print('곱셈')
print(torch.mul(a, b).to_dense() == torch.mul(sparse_a, sparse_b).to_dense())

print('\n')

print('행렬곱')
print(torch.matmul(a, b).to_dense() == torch.matmul(sparse_a, sparse_b).to_dense()) # 에러 발생

덧셈
tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])


곱셈
tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])


행렬곱


NotImplementedError: Could not run 'aten::as_strided' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::as_strided' is only available for these backends: [CPU, MPS, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCPU.cpp:31034 [kernel]
MPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMPS.cpp:22748 [kernel]
Meta: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMeta.cpp:26824 [kernel]
QuantizedCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:929 [kernel]
BackendSelect: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterFunctionalization_0.cpp:20475 [kernel]
Named: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
Conjugate: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/ConjugateFallback.cpp:21 [kernel]
Negative: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/NegateFallback.cpp:23 [kernel]
ZeroTensor: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterZeroTensor.cpp:161 [kernel]
ADInplaceOrView: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/ADInplaceOrViewType_0.cpp:4733 [kernel]
AutogradOther: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradCUDA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHIP: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXLA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradIPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradXPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradHPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradVE: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradLazy: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMeta: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradMTIA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse1: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse2: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradPrivateUse3: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
AutogradNestedTensor: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_0.cpp:15256 [autograd kernel]
Tracer: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/TraceType_0.cpp:16728 [kernel]
AutocastCPU: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:819 [kernel]
FuncTorchVmapMode: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1077 [kernel]
VmapMode: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]
