### Library

In [1]:
import torch
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### 1. Tensor 이해

- 1-1. Tensor 변환
- 1-2. Tensor indexing

#### 1-1. Tensor 변환

In [2]:
# rand: 0과 1 사이의 균일한 분포에서 무작위로 생성된 Tensor 반환
torch.rand(2, 3)

tensor([[0.1835, 0.8359, 0.5250],
        [0.4712, 0.8035, 0.3254]])

In [3]:
# randn: 평균이 0이고 표준 편차가 1인 정규 분포(가우시안 분포)에서 무작위로 생성된 Tensor 반환
torch.randn(2, 3)

tensor([[-0.5660, -1.5616,  0.0110],
        [-0.0853,  1.1672, -0.2982]])

In [4]:
# randint : 주어진 범위 내에서 정수값을 무작위로 선택하여 Tensor 생성 (단, 최솟값을 포함하고, 최댓값은 포함하지 않음)
torch.randint(1, 10, (5, 5)) # 최소값: 1, 최대값: 10, 크기: 5X5

tensor([[4, 1, 1, 6, 1],
        [7, 3, 3, 3, 4],
        [9, 4, 1, 5, 9],
        [7, 6, 4, 5, 8],
        [1, 7, 1, 2, 9]])

In [5]:
# 모든 요소가 0인 Tensor 생성
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# 모든 요소가 1인 3X3 Tensor 생성
torch.ones(2, 2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [7]:
# full: 모든 요소가 지정된 값인 Tensor 반환
torch.full((2, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [8]:
# eye: 단위 행렬 반환
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

- Tensor 형태로 변환
- list, tuple, numpy array 형태로 변환

In [9]:
# list, tuple, numpy array 형태로 변환
li = [[1, 2, 3], [4, 5, 6]]
tu = tuple([1, 2, 3])
np_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# torch.tensor(li) # 2D Tensor
# torch.tensor(tu) # 2D Tensor
# torch.tensor(np_arr) # 2D Tensor

print(f"{torch.tensor(li)}\n") # 2D Tensor
print(f"{torch.tensor(tu)}\n") # 1D Tensor
print(f"{torch.tensor(np_arr)}\n") # 3D Tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([1, 2, 3])

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])



- 다양한 형식의 Tensor 변환
- as_tensor: 변환 전 데이터와 메모리 공유를 사용하므로, 변환 전 데이터 변경 시 변환되어 있는 텐서에도 반영

In [10]:
print("torch.tensor")
data1 = np.array([1, 2, 3, 4, 5])
tensor1 = torch.tensor(data1)
data1[0] = 10 # 0번 index 값 변경: Pandas 의 copy() 와 동일
print(tensor1)

print("-" * 50)

print("torch.as_tensor")
data2 = np.array([1, 2, 3, 4, 5])
tensor2 = torch.as_tensor(data2)
data2[0] = 10 # 0번 index 값 변경: ex: df2 = df1, 즉 메모리 주소 공유
print(tensor2)

torch.tensor
tensor([1, 2, 3, 4, 5])
--------------------------------------------------
torch.as_tensor
tensor([10,  2,  3,  4,  5])


- Tensor: float32 type 으로 변환

In [11]:
data = [1, 2, 3, 4, 5]

tensor1 = torch.tensor(data) # tensor1 = torch.tensor(data, dtype=torch.float32) < 가능
print("torch.tensor")
print("Output: ", tensor1)
print("Type: ", tensor1.dtype)

print("-" * 50)

tensor2 = torch.Tensor(data) # 대문자 Tensor: flaot32 type
print("torch.tensor")
print("Output: ", tensor2)
print("Type: ", tensor2.dtype)

torch.tensor
Output:  tensor([1, 2, 3, 4, 5])
Type:  torch.int64
--------------------------------------------------
torch.tensor
Output:  tensor([1., 2., 3., 4., 5.])
Type:  torch.float32


#### 1-2. Tensor indexing

- Indexing: 텐서 내의 특정 요소를 index를 통해 접근할 수 있는 방법을 의미

In [12]:
# 1D Tensor indexing
tmp_1d = torch.tensor([i for i in range(10)])

print(tmp_1d[0]) # 0 번째 원소
print(tmp_1d[5]) # 6 번째 원소
print(tmp_1d[-1]) # 뒤에서 첫 번째 원소

tensor(0)
tensor(5)
tensor(9)


In [13]:
# 3D Tensor Indexing
tmp_3dim = torch.randn(4, 3, 2) # 4채널, 3행, 2열
print("Shape : ", tmp_3dim.shape)
print(tmp_3dim)

print('-------'*8)

print(tmp_3dim[:,:,0].shape)
print(tmp_3dim[:,:,0]) # 전체 채널과 전체 행에서 0번째 열만 추출
print('\n') 

print(tmp_3dim[0,:,1].shape)
print(tmp_3dim[0,:,1]) # 0번째 채널의 전체 행에서 1번째 열만 추출

Shape :  torch.Size([4, 3, 2])
tensor([[[-0.1914,  0.3749],
         [-1.4432,  0.5782],
         [-1.2428,  1.2672]],

        [[-0.5763,  0.0717],
         [ 0.8030, -0.6033],
         [-0.0178, -0.5389]],

        [[ 0.0721, -0.4412],
         [ 0.4872,  1.7534],
         [ 1.5512, -0.5595]],

        [[-0.4691,  0.1331],
         [ 0.3724, -1.6651],
         [-0.5307,  0.5846]]])
--------------------------------------------------------
torch.Size([4, 3])
tensor([[-0.1914, -1.4432, -1.2428],
        [-0.5763,  0.8030, -0.0178],
        [ 0.0721,  0.4872,  1.5512],
        [-0.4691,  0.3724, -0.5307]])


torch.Size([3])
tensor([0.3749, 0.5782, 1.2672])


- indexing_select: 선택한 차원에서 인덱스에 해당하는 요소만 추출

In [14]:
# index_select
tmp_2d = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(tmp_2d)

select_idx = torch.tensor([0, 2]) # 선택하고자 하는 index는 Tesor 형태여야 함
torch.index_select(tmp_2d, dim=1, index=select_idx)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


tensor([[ 0,  2],
        [10, 12]])

- Masking 을 이용한 indexing: 조건문으로 반환 

In [15]:
mask = tmp_2d > 5
print(mask)
tmp_2d[mask]

tensor([[False, False, False, False, False, False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]])


tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

- masked_select: 마스크 형태의 텐서를 입력으로 받아, 마스크가 True인 요소만 선택하여 반환

In [16]:
# Boolean type 이여야 함
torch.masked_select(tmp_2d, mask=mask)

tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

- take: 텐서를 1D로 펼친 후, 지정한 index의 값을 추출

In [17]:
tmp_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(f"{tmp_2dim}\n")
select_idx = torch.tensor([0, 8])
torch.take(tmp_2dim, index=select_idx)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])



tensor([0, 8])

- gather: 주어진 차원에서 인덱스에 해당하는 요소들을 선택해 새로운 Tensor 를 반환

In [18]:
tmp_2dim = torch.tensor([[i for i in range(10)], [i for i in range(10, 20)]])
print(f"{tmp_2dim}\n")

recon_idx = torch.tensor([[0, 1], [6, 8]])
print(f"{recon_idx}")

dim = 1
torch.gather(tmp_2dim, dim=dim, index=recon_idx)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

tensor([[0, 1],
        [6, 8]])


tensor([[ 0,  1],
        [16, 18]])

### 2. Tensor 모양 변경

- 2-1. Tensor 의 shape을 변경 
- 2-2. Tensor 의 차원 추가 및 변경
- 2-3. 역할이 비슷한 함수들의 차이

#### 2-1. Tensor 의 shape을 변경 

- size(): Tensor 모양 확인

In [19]:
# shape 과 동일한 기능
a = torch.randn(2, 3, 5)
print(f"size: {a.size()}")
print(f"shape: {a.shape}")

size: torch.Size([2, 3, 5])
shape: torch.Size([2, 3, 5])


- reshape: 텐서의 모양을 변경하는 함수
- 원소의 개수가 같은 경우에만 차원 변경이 가능
- `-1` 값으로 모양을 자동 설정이 가능
- 인자의 개수 → 차원 수 (몇 D인지)
- 각 인자의 값 → 각 차원의 크기

```
reshape(3)       → 1D, shape: [3]  
reshape(2, 3)    → 2D, shape: [2, 3]  
reshape(2, 1, 3) → 3D, shape: [2, 1, 3]
```

In [20]:
a = torch.randn(2, 3, 5) # 총 원소 개수: 2 × 3 × 5 = 30
print(a)
print(f"Shape{a.size()}\n")

reshape_a = a.reshape(5, 6) # 5 × 6 = 30 → 가능
print(reshape_a)
print(f"Reshape: {reshape_a.size()}")

tensor([[[ 0.8198,  0.0494, -1.3109, -0.1636,  1.6400],
         [-1.3788, -0.2461, -0.5478, -0.5957, -2.0575],
         [-2.3355,  2.4780,  0.9869, -1.5096,  0.8367]],

        [[ 0.0483,  1.3701,  0.4443, -0.9005,  1.2575],
         [-0.7565,  0.0971,  1.6997,  1.4092,  1.1849],
         [ 0.2539,  0.0479, -0.7888, -0.3168, -0.1271]]])
Shapetorch.Size([2, 3, 5])

tensor([[ 0.8198,  0.0494, -1.3109, -0.1636,  1.6400, -1.3788],
        [-0.2461, -0.5478, -0.5957, -2.0575, -2.3355,  2.4780],
        [ 0.9869, -1.5096,  0.8367,  0.0483,  1.3701,  0.4443],
        [-0.9005,  1.2575, -0.7565,  0.0971,  1.6997,  1.4092],
        [ 1.1849,  0.2539,  0.0479, -0.7888, -0.3168, -0.1271]])
Reshape: torch.Size([5, 6])


In [21]:
# -1로 모양 자동 변경
reshape_auto_a = a.reshape(3, -1) # 앞 원소를 지정
print(f"Reshape A: {reshape_auto_a.size()}")

reshape_auto_b = a.reshape(-1, 5) # 뒤 원소를 지정
print(f"Reshape B: {reshape_auto_b.size()}")

Reshape A: torch.Size([3, 10])
Reshape B: torch.Size([6, 5])


- reshape(4, -1) 같은 경우, 전체 원소 수가 4로 나누어떨어지지 않으면 Error 발생

In [22]:
reshape_auto_c = a.reshape(4, -1) # 앞 원소를 지정
print(f"Reshape C: {reshape_auto_c.size()}")

RuntimeError: shape '[4, -1]' is invalid for input of size 30

- view: Tensor 의 모양을 변경하는 함수
- reshape 과 동일한 기능

In [23]:
view_auto_a = a.view(3, -1) # 앞 원소를 지정
print(f"View A: {view_auto_a.size()}")

view_auto_b = a.view(-1, 5) # 뒤 원소를 지정
print(f"View B: {view_auto_b.size()}")

View A: torch.Size([3, 10])
View B: torch.Size([6, 5])


- transpose: Tensor 의 차원을 변경하는 함수

In [24]:
tensor_a = torch.randint(1, 10, (3, 2, 5))
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

tensor_a = tensor_a.transpose(1, 2) # 위 (3, 2, 5) → (3, 5, 2) 로 변경
print(tensor_a)
print(f"Shape: {tensor_a.size()}")

tensor([[[4, 8, 1, 5, 2],
         [7, 4, 6, 2, 7]],

        [[3, 4, 5, 2, 6],
         [2, 8, 9, 2, 3]],

        [[9, 7, 1, 8, 5],
         [4, 1, 1, 1, 9]]])
Shape: torch.Size([3, 2, 5])

tensor([[[4, 7],
         [8, 4],
         [1, 6],
         [5, 2],
         [2, 7]],

        [[3, 2],
         [4, 8],
         [5, 9],
         [2, 2],
         [6, 3]],

        [[9, 4],
         [7, 1],
         [1, 1],
         [8, 1],
         [5, 9]]])
Shape: torch.Size([3, 5, 2])


- permute: 차원 순서를 변경하는 함수

In [25]:
print(tensor_a)
print("Shape : ", tensor_a.size())
print('\n')

permute_a = tensor_a.permute(0, 2, 1) # (3,2,5)의 모양을 (3,5,2)의 모양으로 변경
print(permute_a)
print("Shape : ", permute_a.size())

tensor([[[4, 7],
         [8, 4],
         [1, 6],
         [5, 2],
         [2, 7]],

        [[3, 2],
         [4, 8],
         [5, 9],
         [2, 2],
         [6, 3]],

        [[9, 4],
         [7, 1],
         [1, 1],
         [8, 1],
         [5, 9]]])
Shape :  torch.Size([3, 5, 2])


tensor([[[4, 8, 1, 5, 2],
         [7, 4, 6, 2, 7]],

        [[3, 4, 5, 2, 6],
         [2, 8, 9, 2, 3]],

        [[9, 7, 1, 8, 5],
         [4, 1, 1, 1, 9]]])
Shape :  torch.Size([3, 2, 5])


#### 2-2. Tensor 의 차원 추가 및 변경

- unsqueeze: Tensor 에 특정 차원에 크기가 1인 차원을 추가

In [26]:
tensor_a = torch.tensor([i for i in range(10)]).reshape(5, 2) # 2D Tensor 변환
print(tensor_a)
print(f"Shape: {tensor_a.size()}\n")

unsqu_a = tensor_a.unsqueeze(0) # 0번째 차원에 차원 추가 > (5, 2) → (1, 5, 2)
print(unsqu_a)
print(f"Shape: {unsqu_a.size()}")

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Shape: torch.Size([5, 2])

tensor([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]])
Shape: torch.Size([1, 5, 2])


In [27]:
unsqu_b = tensor_a.unsqueeze(-1) # 마지막 차원에 차원 추가 > (5, 2) → (5, 2, 1)
print(unsqu_b)
print(f"Shape: {unsqu_b.size()}")

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]],

        [[6],
         [7]],

        [[8],
         [9]]])
Shape: torch.Size([5, 2, 1])


- squeeze: 텐서의 차원을 줄이는 함수

In [28]:
print(unsqu_a)
print("Shape : ", unsqu_a.size())
print('\n')

squ = unsqu_a.squeeze() # 차원이 1인 차원을 제거
print(squ)
print("Shape : ", squ.size())

tensor([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]])
Shape :  torch.Size([1, 5, 2])


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Shape :  torch.Size([5, 2])


In [29]:
x = torch.zeros(2, 1, 2, 1, 2) # 모든 원소가 0인 (2,1,2,1,2) 크기를 가지는 텐서
print("Shape (original) : ", x.size()) # 원래 텐서 크기
print('\n')

print("Shape (squeeze()) :", x.squeeze().size()) # 차원이 1인 차원이 여러개일 때, 모든 차원이 1인 차원 제거
print('\n')

print("Shape (squeeze(0)) :", x.squeeze(0).size()) # 0번째 차원은 차원의 크기가 1이 아니므로, 변화 없음
print('\n')

print("Shape (squeeze(1)) :", x.squeeze(1).size()) # 1번째 차원은 차원의 크기가 1이므로 제거
print('\n')

print("Shape (squeeze(0,1,3)) :", x.squeeze((0, 1, 3)).size()) # 여러 차원 제거 가능 (0번째 차원은 차원의 크기가 1이 아니기 때문에 무시)

Shape (original) :  torch.Size([2, 1, 2, 1, 2])


Shape (squeeze()) : torch.Size([2, 2, 2])


Shape (squeeze(0)) : torch.Size([2, 1, 2, 1, 2])


Shape (squeeze(1)) : torch.Size([2, 2, 1, 2])


Shape (squeeze(0,1,3)) : torch.Size([2, 2, 2])


- expand: Tensor 의 값을 메모리에 복제하지 않고 1인 차원을 원하는 크기만큼 늘려서 “그렇게 보이게” 만드는 함수
- `expand()` 는 1인 차원만 확장 가능
- `expand()` 는 차원 수는 유지하면서 shape만 늘려서 구조를 바꾸는 것”

In [30]:
tensor_1dim = torch.tensor([1, 2, 3, 4])
print(tensor_1dim)
print(f"Shape: {tensor_1dim.size()}\n")

expand_tensor = tensor_1dim.expand(3, 4) # (,4) 를 (3,4) 의 크기로 확장 (값을 반복)
print(expand_tensor)
print(f"Shape: {expand_tensor.size()}")

tensor([1, 2, 3, 4])
Shape: torch.Size([4])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
Shape: torch.Size([3, 4])


In [31]:
tensor_2dim = torch.tensor([[1, 2, 3, 4], [1, 2, 3, 4]]) # (2,4) 크기를 가진 Tensor
print(tensor_2dim)
print(f"Shape: {tensor_2dim.size()}\n")
print('\n')

expand_tensor = tensor_2dim.expand(4,4) # (2,4) 를 (4,8) 의 크기로 확장 (값을 반복)
print(expand_tensor) # 에러 발생
print("Shape : ", expand_tensor.size()) # 에러 발생

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])
Shape: torch.Size([2, 4])





RuntimeError: The expanded size of the tensor (4) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [4, 4].  Tensor sizes: [2, 4]

- repeat: Tensor 의 값을 반복하여 크기 확장
- repeat()는 실제 값을 복사, 반복해서 데이터 수를 늘림
- 정말 값을 복제해야 하거나, shape 제한이 걸릴 때 → `repeat()` 사용

In [36]:
tensor_1dim = torch.tensor([1, 2, 3, 4])
print(tensor_1dim)
print(f"Shape: {tensor_1dim.size()}\n")

repeat_tensor = tensor_1dim.repeat(3, 4) # (4,) 를 (3,4) 의 크기로 반복
print(repeat_tensor)
print(f"repeat Shape: {repeat_tensor.size()}\n")

expand_tensor = tensor_1dim.expand(3, 4) # (,4) 를 (3,4) 의 크기로 확장 (값을 반복)
print(expand_tensor)
print(f"expand Shape: {expand_tensor.size()}")

tensor([1, 2, 3, 4])
Shape: torch.Size([4])

tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])
repeat Shape: torch.Size([3, 16])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])
expand Shape: torch.Size([3, 4])


Flatten이란?

- CNN 출력 텐서 `(batch_size, channels, height, width)` → FC 레이어 입력을 위해 2D로 변환 필요
- `flatten(start_dim=1)` 사용 → `channels × height × width`를 한 줄로 펼쳐 `(batch_size, features)` 형태로 변환
- FC 레이어는 `(batch_size, features)` 형태의 2D만 입력 가능

- ex  
`x.shape → [32, 64, 7, 7]`  
`x.flatten(start_dim=1).shape → [32, 3136]` 

- flatten: 다차원 Tensor 를 줄이고 1차원으로 변환
- 다차원 Tensor 를 1D Tensor 로 변환


In [43]:
t = torch.tensor([i for i in range(20)]).reshape(2, 5, 2) # 3D Tensor
print(t)
print(f"Shape: {t.size()}\n")

flatten_tensor = t.flatten() # 1D Tensor로 변환
print(flatten_tensor)
print(f"Shape: {flatten_tensor.size()}")

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9]],

        [[10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19]]])
Shape: torch.Size([2, 5, 2])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
Shape: torch.Size([20])


In [47]:
flatten_tensor2 = t.flatten(start_dim=1) # 2D Tensor로 변환
print(f"Start Dim: 1: {flatten_tensor2}")
print(f"Start Dim 1 Shape: {flatten_tensor2.shape}")

Start Dim: 1: tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
Start Dim 1 Shape: torch.Size([2, 10])



- ravel: 다차원 Tensor를 1D Tensor로 변환 (flatten 과 동일)
- flatten 과 달리 어떤 축을 기준으로 평탄화 하는 작업이 없음
- ex
`t.ravel(1)` < Error

In [49]:
print(t.ravel())
print(t.ravel(1))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


TypeError: _TensorBase.ravel() takes no arguments (1 given)

#### 2-3. 역할이 비슷한 함수들의 차이

- 모양 변경: `view` Vs `reshape` VS `unsqueeze`
- contiguous 란?
    - Tensor 의 메모리 상에 연속적인 데이터 batch 를 갖는 것
    - Tensor 를 처음 생성 후 정의하면 기본적으로 contiguous 하지만
    - 이에 대해 차원의 순서를 변경하는 과정을 거치면 contiguous 하지 않음
    - Tensor 의 contiguous 를 하기 위해선 `is_contiguous()` 사용
    - 즉, Tensor 의 shape 과 실제 저장된 순서가 일치하면 `contiguous=True`
        - 아니라면 `contiguous=False` 

- view 는 contiguous 하지 않은 Tensor 에 대해서 동작하지 않음
- reshape 은 contiguous 하지 않은 Tensor 를 contiguous 하게 만들고 크기를 변경함
- unsqueeze 는 차원의 크기가 1인 차원을 추가하지만 차원의 크기가 1이 아니라면 차원의 모양을 변경할 수 없음

In [54]:
# view vs reshape
tmp = torch.tensor([[[0, 1], [2, 3], [4, 5]], \
                 [[6, 7], [8, 9], [10, 11]], \
                 [[12, 13], [14, 15], [16, 17]], \
                 [[18, 19], [20, 21], [22, 23]]])
tmp_t = tmp.transpose(0,1) # contiguous 를 False 로 만들기 위한 작업
print(tmp_t.is_contiguous()) # contiguous 한지 검사
print(tmp_t.view(-1)) # view는 contiguous 하지 않은 텐서에 대해선 동작이 되지 않음

False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [55]:
reshape_tmp = tmp_t.reshape(-1) # reshape은 contiguous 하지 않아도 동작이 됨
print(reshape_tmp)
print(reshape_tmp.is_contiguous()) # contiguous 하지 않았던 Tensor를 contiguous 하게 변경해 줌

tensor([ 0,  1,  6,  7, 12, 13, 18, 19,  2,  3,  8,  9, 14, 15, 20, 21,  4,  5,
        10, 11, 16, 17, 22, 23])
True


In [56]:
# (view , reshape) vs unsqueeze
tensor_a = torch.randn(2, 3)
# (2, 3) 의 텐서를 (2, 3, 1)의 크기로 변경
view_tensor = tensor_a.view(2, 3, 1) # view 를 이용하여 (2,3,1) 의 크기로 변경
reshape_tensor = tensor_a.reshape(2, 3, 1) # reshape 를 이용하여 (2,3,1) 의 크기로 변경
unsqueeze_tensor = tensor_a.unsqueeze(-1) # unsqueeze 를 이용하여 (2,3,1) 의 크기로 변경

print("View output size : ",view_tensor.size())
print("Reshape output size : ",reshape_tensor.size())
print("Unsqueeze output size : ",unsqueeze_tensor.size())

View output size :  torch.Size([2, 3, 1])
Reshape output size :  torch.Size([2, 3, 1])
Unsqueeze output size :  torch.Size([2, 3, 1])


- 차원 변경 : transpose vs. permute
 - transpose : 두 차원에 대해서만 변경이 가능
   - 인자가 총 2개여야함.
 - permute : 모든 차원에 대해서 변경이 가능
   - 인자가 차원의 개수와 동일해야 함.

In [57]:
tensor_a = torch.randn(2, 3, 2)
transpose_tensor = tensor_a.transpose(2, 1) # 행과 열을 전치
permute_tensor = tensor_a.permute(0, 2, 1) # 행과 열을 바꿈.

print("Transpose tensor shape : ", transpose_tensor.size())
print("Permute tensor shape : ", permute_tensor.size())

Transpose tensor shape :  torch.Size([2, 2, 3])
Permute tensor shape :  torch.Size([2, 2, 3])


In [58]:
print(tensor_a.permute(1, 2, 0).shape)
print(tensor_a.transpose(2, 1).transpose(0, 2).shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


### 3. Tensor 합치기 및 나누기

- 3-1. 여러 Tensor 를 합치는 방법
- 3-2. 하나의 Tensor 를 여러 텐서로 나누는 방법

#### 3-1. 여러 Tensor 를 합치는 방법

- cat : 주어진 차원을 따라 Tensor 들을 연결

In [59]:
tensor_a = torch.randint(1, 10, (2, 3)) # 1부터 9까지의 무작위 정수가 있는 (2,3) Tensor
tensor_b = torch.rand(5, 3) # 0부터 1까지의 균등분포를 따르는 (5,3) Tensor

print("Tensor A shape : ", tensor_a.size())
print(tensor_a)

print('\n')

print("Tensor B shape : ", tensor_b.size())
print(tensor_b)

print('\n')

a_cat_b_row = torch.cat((tensor_a, tensor_b), dim=0) # dim = 0 (행), Tensor A 와 Tensor B 를 행 기준으로 합친다.
print("Concat Tensor A and B (by row) Shape : ", a_cat_b_row.shape) # (Tensor A 행 개수 + Tensor B 행 개수, Tensor A/B 열 개수)
print(a_cat_b_row)

Tensor A shape :  torch.Size([2, 3])
tensor([[6, 5, 8],
        [4, 8, 9]])


Tensor B shape :  torch.Size([5, 3])
tensor([[0.3165, 0.9815, 0.0851],
        [0.7329, 0.1316, 0.2577],
        [0.5521, 0.8987, 0.2881],
        [0.4396, 0.1786, 0.3598],
        [0.9799, 0.3538, 0.4739]])


Concat Tensor A and B (by row) Shape :  torch.Size([7, 3])
tensor([[6.0000, 5.0000, 8.0000],
        [4.0000, 8.0000, 9.0000],
        [0.3165, 0.9815, 0.0851],
        [0.7329, 0.1316, 0.2577],
        [0.5521, 0.8987, 0.2881],
        [0.4396, 0.1786, 0.3598],
        [0.9799, 0.3538, 0.4739]])


- stack : 주어진 차원을 새로운 차원으로 추가하여 Tensor 들을 쌓음
- 합쳐질 Tensor 의 크기는 모두 같아야함

In [60]:
tensor_a = torch.randint(1, 10, (3, 2))  # 1부터 9까지의 무작위 정수가 있는 (3,2) Tensor
tensor_b = torch.rand(3, 2)  # 0부터 1까지의 균등분포를 따르는 (3,2) Tensor

print("Tensor A shape : ", tensor_a.size())
print(tensor_a)

print('\n')

print("Tensor B shape : ", tensor_b.size())
print(tensor_b)

print('\n')

stack_tensor_row = torch.stack([tensor_a, tensor_b], dim=0)  # dim = 0, 행을 기준으로 Tensor A 에 Tensor B 를 쌓기
print("Stack A and B (by row): ", stack_tensor_row.size()) # (쌓은 Tensor 개수, Tensor A/B 행 개수, Tensor A/B 열 개수)
print(stack_tensor_row)

Tensor A shape :  torch.Size([3, 2])
tensor([[9, 2],
        [8, 1],
        [7, 9]])


Tensor B shape :  torch.Size([3, 2])
tensor([[0.1700, 0.1688],
        [0.9301, 0.5784],
        [0.9493, 0.1968]])


Stack A and B (by row):  torch.Size([2, 3, 2])
tensor([[[9.0000, 2.0000],
         [8.0000, 1.0000],
         [7.0000, 9.0000]],

        [[0.1700, 0.1688],
         [0.9301, 0.5784],
         [0.9493, 0.1968]]])


#### 3-2. 하나의 Tensor 를 여러 텐서로 나누는 방법

- chunk: 나누고자 하는 Tensor 의 개수를 지정해서 원래의 Tensor 개수 만큼 분리
- chunk 인자: 몇 개의 Tensor 나눌지 지정

In [61]:
tensor_a = torch.randint(1, 10, (6, 4))  # (6,4) 텐서
print("Original : ", tensor_a)

print('\n')

chunk_num = 3
chunk_tensor = torch.chunk(tensor_a, chunks = chunk_num, dim=0)  # dim = 0 (행), 6개의 행이 3개로 나누어 떨어지므로 3개의 텐서로 분리
print(f'{len(chunk_tensor)} 개의 Tensor로 분리')

print('\n')

for idx,a in enumerate(chunk_tensor):
    print(f'{idx} 번째 Tensor \n{a}')
    print(f'{idx} 번째 Tensor 크기', a.size())
    print('---'*10)

Original :  tensor([[7, 8, 6, 6],
        [4, 5, 1, 6],
        [5, 1, 5, 7],
        [5, 1, 2, 5],
        [6, 1, 5, 2],
        [1, 9, 4, 8]])


3 개의 Tensor로 분리


0 번째 Tensor 
tensor([[7, 8, 6, 6],
        [4, 5, 1, 6]])
0 번째 Tensor 크기 torch.Size([2, 4])
------------------------------
1 번째 Tensor 
tensor([[5, 1, 5, 7],
        [5, 1, 2, 5]])
1 번째 Tensor 크기 torch.Size([2, 4])
------------------------------
2 번째 Tensor 
tensor([[6, 1, 5, 2],
        [1, 9, 4, 8]])
2 번째 Tensor 크기 torch.Size([2, 4])
------------------------------


- split: 입력한 크기로 여러 개의 작은 Tensor로 나눔
- split_size_or_sections 인자
    - split_size (int): 얼마만큼의 크기로 자를 것인지
    - sections (list): 얼마만큼의 크기로 각각 자를 것인지 (리스트 형태로 각 텐서의 크기를 각각 지정해 줄 수 있음)

In [62]:
tensor_a = torch.randint(1, 10, (6, 4))  # (6,4) 텐서
print(tensor_a)

print('\n')

split_size = 2
split_tensor = torch.split(tensor_a , split_size_or_sections = split_size, dim=0)  # dim = 0 (행), 텐서 A 를 행의 길이가 2 (split_size)인 텐서로 나눔
print(f'{len(split_tensor)} 개의 Tensor로 분리')

print('\n')

for idx,a in enumerate(split_tensor):
    print(f'{idx} 번째 Tensor \n{a}')
    print(f'{idx} 번째 Tensor 크기', a.size())
    print('---'*10)

tensor([[2, 2, 4, 6],
        [9, 7, 9, 9],
        [9, 5, 1, 8],
        [1, 6, 7, 7],
        [2, 7, 4, 8],
        [9, 6, 2, 3]])


3 개의 Tensor로 분리


0 번째 Tensor 
tensor([[2, 2, 4, 6],
        [9, 7, 9, 9]])
0 번째 Tensor 크기 torch.Size([2, 4])
------------------------------
1 번째 Tensor 
tensor([[9, 5, 1, 8],
        [1, 6, 7, 7]])
1 번째 Tensor 크기 torch.Size([2, 4])
------------------------------
2 번째 Tensor 
tensor([[2, 7, 4, 8],
        [9, 6, 2, 3]])
2 번째 Tensor 크기 torch.Size([2, 4])
------------------------------
